### ISSUE TITLE
WX_APP_ID not found. Declare it as envvar or define a default value.

### ISSUE THREAD

**Issue by lop1992** [pointworld/wxbox#1]
你好,下载下来 运行test.py ..结果是,
File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: WX_APP_ID not found. Declare it as envvar or define a default value.

**Comment by pointworld** [comment]
需要将根目录下的 env 文件更改为 .env，并在里面配置好你自己的相关参数就可以了，因为这里使用了 python-decouple 包来分离敏感的配置信息

**Comment by lop1992** [comment]
> 
> 
> 需要将根目录下的 env 文件更改为 .env，并在里面配置好你自己的相关参数就可以了，因为这里使用了 python-decouple 包来分离敏感的配置信息

非常感谢!
